name: Publish Site

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [10.x]

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@771cd2231aa5d8d9a64a6dce771dcac9e2afa20a
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          cname: kartiniteknologi.id
          hugoVersion: extended_0.55.0
          args: --minify --cleanDestinationDir
      - name: Caching dependencies 
        uses: actions/cache@v2
        with:
          path: |
            ~/.local/share/renv
            ~/.npm
            **/node_modules
          key: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
